nelmio_api_doc:
    documentation:
        info:
            title: Arama Motoru API
            description: İçerik arama ve sıralama servisi
            version: 1.0.0
        paths: {}
    areas:
        path_patterns:
            - ^/api(?!/doc$)
